// GENERATED by tools/gen_effect_catalog.py — DO NOT EDIT
// Regenerate: PMS_DESKTOP=../pop-maker-studio python3 tools/gen_effect_catalog.py
//
// Video effects come from $PMS_DESKTOP/effects/mcp_manifest.json.
// Audio effects use engine vocabulary ids and the exact param keys read by
// the engine's add_effect_brick / add_audio_multifx_brick handlers
// (src/ipc_server.cpp); ranges/defaults from src/audio_fx.h (AudioFX).

import Foundation

struct EffectDef: Identifiable, Hashable {
    let id: String
    let name: String
    let category: String
    let description: String
    let params: [Param]
    struct Param: Hashable {
        let key: String
        let label: String
        let min: Double
        let max: Double
        let def: Double
        let format: String
    }
}

enum EffectCatalog {
    // Video effects (109) — from effects/mcp_manifest.json, manifest order.
    static let video: [EffectDef] = [
        EffectDef(
            id: "pixelate",
            name: "Pixelate",
            category: "Glitch",
            description: "Mosaic pixel art  ·  lo-fi crunch  ·  adjustable block size",
            params: [
                .init(key: "size", label: "Block Size", min: 1.0, max: 64.0, def: 12.0, format: "%.0f px"),
            ]
        ),
        EffectDef(
            id: "film_grain",
            name: "Film Grain",
            category: "Film",
            description: "Analog film noise  ·  luma-weighted grain  ·  cinematic texture",
            params: [
                .init(key: "intensity", label: "Intensity", min: 0.0, max: 1.0, def: 0.4, format: "%.2f"),
                .init(key: "size", label: "Grain Size", min: 0.5, max: 4.0, def: 1.0, format: "%.1f"),
            ]
        ),
        EffectDef(
            id: "scanlines",
            name: "Scanlines",
            category: "Pattern",
            description: "CRT horizontal lines  ·  interlace look  ·  retro monitor",
            params: [
                .init(key: "density", label: "Line Density", min: 1.0, max: 6.0, def: 2.0, format: "%.1f"),
            ]
        ),
        EffectDef(
            id: "chromatic_aberration",
            name: "Chromatic Aberration",
            category: "Glitch",
            description: "Lens color fringing  ·  R/B channel split  ·  radial distortion",
            params: []
        ),
        EffectDef(
            id: "duotone",
            name: "Duotone",
            category: "Color",
            description: "Two-color gradient map  ·  shadow/highlight toning  ·  poster look",
            params: [
                .init(key: "shadow_r", label: "Shadow R", min: 0.0, max: 1.0, def: 0.05, format: "%.2f"),
                .init(key: "shadow_g", label: "Shadow G", min: 0.0, max: 1.0, def: 0.02, format: "%.2f"),
                .init(key: "shadow_b", label: "Shadow B", min: 0.0, max: 1.0, def: 0.2, format: "%.2f"),
                .init(key: "highlight_r", label: "Highlight R", min: 0.0, max: 1.0, def: 1.0, format: "%.2f"),
                .init(key: "highlight_g", label: "Highlight G", min: 0.0, max: 1.0, def: 0.85, format: "%.2f"),
                .init(key: "highlight_b", label: "Highlight B", min: 0.0, max: 1.0, def: 0.1, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "neon_glow",
            name: "Neon Glow",
            category: "Light",
            description: "Edge bloom  ·  oversaturated halo  ·  cyberpunk",
            params: [
                .init(key: "width", label: "Glow Width", min: 1.0, max: 8.0, def: 3.0, format: "%.1f px"),
            ]
        ),
        EffectDef(
            id: "thermal",
            name: "Thermal",
            category: "Color",
            description: "Infrared heat map  ·  iron palette  ·  night-cam look",
            params: []
        ),
        EffectDef(
            id: "night_vision",
            name: "Night Vision",
            category: "Color",
            description: "Amplified green channel  ·  phosphor noise  ·  vignette",
            params: [
                .init(key: "noise", label: "Static", min: 0.0, max: 1.0, def: 0.3, format: "%.2f"),
                .init(key: "gain", label: "Gain", min: 0.5, max: 3.0, def: 1.2, format: "%.1f"),
            ]
        ),
        EffectDef(
            id: "old_film",
            name: "Old Film",
            category: "Film",
            description: "Sepia  ·  scratches  ·  flicker  ·  aged look",
            params: [
                .init(key: "sepia", label: "Sepia", min: 0.0, max: 1.0, def: 0.8, format: "%.2f"),
                .init(key: "scratch", label: "Scratches", min: 0.0, max: 1.0, def: 0.4, format: "%.2f"),
                .init(key: "flicker", label: "Flicker", min: 0.0, max: 1.0, def: 0.2, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "holographic",
            name: "Holographic",
            category: "Glitch",
            description: "Rainbow iridescent overlay  ·  angle-dependent hue shift  ·  foil",
            params: [
                .init(key: "speed", label: "Speed", min: 0.0, max: 4.0, def: 1.0, format: "%.1f"),
            ]
        ),
        EffectDef(
            id: "rgb_split",
            name: "RGB Split",
            category: "Glitch",
            description: "Animated channel separation  ·  beat-reactive offset  ·  digital tear",
            params: [
                .init(key: "intensity", label: "Intensity", min: 0.0, max: 1.0, def: 0.3, format: "%.2f"),
                .init(key: "speed", label: "Speed", min: 0.0, max: 4.0, def: 1.0, format: "%.1f"),
            ]
        ),
        EffectDef(
            id: "posterize",
            name: "Posterize",
            category: "Color",
            description: "Quantized color steps  ·  screen-print look  ·  comic poster",
            params: [
                .init(key: "levels", label: "Color Levels", min: 2.0, max: 16.0, def: 4.0, format: "%.0f"),
            ]
        ),
        EffectDef(
            id: "halftone",
            name: "Halftone",
            category: "Pattern",
            description: "Dot grid print  ·  newsprint  ·  pop art raster",
            params: [
                .init(key: "size", label: "Dot Size", min: 2.0, max: 20.0, def: 6.0, format: "%.0f px"),
            ]
        ),
        EffectDef(
            id: "fisheye",
            name: "Fisheye",
            category: "Warp",
            description: "Barrel distortion  ·  wide-angle lens warp  ·  GoPro look",
            params: []
        ),
        EffectDef(
            id: "bleach_bypass",
            name: "Bleach Bypass",
            category: "Color",
            description: "High contrast desaturated  ·  film processing look  ·  gritty",
            params: []
        ),
        EffectDef(
            id: "color_burn",
            name: "Color Burn",
            category: "Color",
            description: "Burn blend mode overlay  ·  deep shadow crush  ·  fire palette",
            params: [
                .init(key: "hue", label: "Hue Shift", min: 0.0, max: 360.0, def: 0.0, format: "%.0f°"),
            ]
        ),
        EffectDef(
            id: "crt",
            name: "CRT",
            category: "Pattern",
            description: "Screen curvature  ·  phosphor glow  ·  scanlines  ·  border",
            params: [
                .init(key: "curvature", label: "Curvature", min: 0.05, max: 1.0, def: 0.35, format: "%.2f"),
                .init(key: "glow", label: "Phosphor", min: 0.0, max: 1.0, def: 0.3, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "sketch",
            name: "Sketch",
            category: "Art",
            description: "Pencil drawing  ·  edge extraction  ·  paper texture",
            params: [
                .init(key: "invert", label: "Invert", min: 0.0, max: 1.0, def: 1.0, format: "%.0f"),
            ]
        ),
        EffectDef(
            id: "glitch_block",
            name: "Glitch Block",
            category: "Glitch",
            description: "Rectangular displacement blocks  ·  heavy digital break  ·  signal loss",
            params: [
                .init(key: "intensity", label: "Intensity", min: 0.0, max: 1.0, def: 0.4, format: "%.2f"),
                .init(key: "speed", label: "Speed", min: 0.0, max: 4.0, def: 1.5, format: "%.1f"),
            ]
        ),
        EffectDef(
            id: "lomo",
            name: "Lomo",
            category: "Color",
            description: "Vignetted  ·  saturated lo-fi  ·  light leaks  ·  toy camera",
            params: [
                .init(key: "vignette", label: "Vignette", min: 0.1, max: 1.0, def: 0.75, format: "%.2f"),
                .init(key: "saturation", label: "Color Pop", min: 0.8, max: 2.0, def: 1.6, format: "%.2f"),
                .init(key: "fade", label: "Fade", min: 0.0, max: 0.5, def: 0.1, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "twirl",
            name: "Twirl",
            category: "Warp",
            description: "Vortex rotation spiraling from center",
            params: [
                .init(key: "radius", label: "Radius", min: 0.1, max: 1.0, def: 0.55, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "ripple",
            name: "Ripple",
            category: "Warp",
            description: "Expanding ring waves from center",
            params: [
                .init(key: "frequency", label: "Frequency", min: 2.0, max: 40.0, def: 18.0, format: "%.0f"),
                .init(key: "amplitude", label: "Amplitude", min: 0.005, max: 0.1, def: 0.035, format: "%.3f"),
                .init(key: "speed", label: "Speed", min: 0.0, max: 6.0, def: 2.0, format: "%.1f"),
            ]
        ),
        EffectDef(
            id: "wave_warp",
            name: "Wave Warp",
            category: "Warp",
            description: "Perpendicular sine-wave displacement field",
            params: [
                .init(key: "freq_x", label: "Freq X", min: 1.0, max: 30.0, def: 8.0, format: "%.0f"),
                .init(key: "freq_y", label: "Freq Y", min: 1.0, max: 30.0, def: 6.0, format: "%.0f"),
                .init(key: "amplitude", label: "Amplitude", min: 0.008, max: 0.12, def: 0.08, format: "%.3f"),
                .init(key: "speed", label: "Speed", min: 0.0, max: 5.0, def: 1.5, format: "%.1f"),
            ]
        ),
        EffectDef(
            id: "breathe",
            name: "Breathe",
            category: "Motion",
            description: "Edge-driven breathing — contours expand and contract along their normals with hue cycling and chromatic fringing",
            params: [
                .init(key: "breathe_rate", label: "Breathe Rate", min: 0.1, max: 3.0, def: 0.8, format: "%.1f"),
                .init(key: "warp_strength", label: "Warp", min: 0.0, max: 0.15, def: 0.04, format: "%.3f"),
                .init(key: "color_speed", label: "Color Drift", min: 0.0, max: 1.0, def: 0.3, format: "%.2f"),
                .init(key: "chroma_split", label: "Chroma Split", min: 0.0, max: 1.0, def: 0.6, format: "%.2f"),
                .init(key: "complexity", label: "Complexity", min: 0.0, max: 1.0, def: 0.5, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "kaleidoscope",
            name: "Kaleidoscope",
            category: "Warp",
            description: "N-way radial mirror symmetry",
            params: [
                .init(key: "segments", label: "Segments", min: 2.0, max: 16.0, def: 8.0, format: "%.0f"),
                .init(key: "rotation", label: "Rotation", min: 0.0, max: 6.28, def: 0.0, format: "%.2f"),
                .init(key: "zoom", label: "Zoom", min: 0.5, max: 3.0, def: 0.55, format: "%.1f"),
            ]
        ),
        EffectDef(
            id: "zoom_blur_rad",
            name: "Zoom Streak",
            category: "Motion",
            description: "Radial motion blur emanating from focal point",
            params: [
                .init(key: "intensity", label: "Intensity", min: 0.0, max: 0.35, def: 0.12, format: "%.2f"),
                .init(key: "cx", label: "Center X", min: 0.0, max: 1.0, def: 0.5, format: "%.2f"),
                .init(key: "cy", label: "Center Y", min: 0.0, max: 1.0, def: 0.5, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "spin_blur",
            name: "Spin Blur",
            category: "Motion",
            description: "Rotational motion blur around center",
            params: [
                .init(key: "angle", label: "Angle", min: 0.01, max: 0.3, def: 0.08, format: "%.3f"),
            ]
        ),
        EffectDef(
            id: "heat_haze",
            name: "Heat Haze",
            category: "Warp",
            description: "Shimmering atmospheric heat distortion",
            params: [
                .init(key: "intensity", label: "Intensity", min: 0.0, max: 2.0, def: 1.8, format: "%.1f"),
                .init(key: "speed", label: "Speed", min: 0.0, max: 4.0, def: 1.5, format: "%.1f"),
            ]
        ),
        EffectDef(
            id: "barrel_warp",
            name: "Barrel Warp",
            category: "Warp",
            description: "Strong barrel / pin-cushion lens distortion",
            params: [
                .init(key: "k1", label: "Barrel", min: 0.05, max: 1.0, def: 0.4, format: "%.2f"),
                .init(key: "k2", label: "Pincush", min: 0.0, max: 0.5, def: 0.1, format: "%.2f"),
                .init(key: "scale", label: "Scale", min: 0.5, max: 1.0, def: 0.9, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "anamorphic_streak",
            name: "Anamorphic Flare",
            category: "Light",
            description: "Horizontal cyan lens streak flares on bright highlights",
            params: [
                .init(key: "threshold", label: "Threshold", min: 0.3, max: 1.0, def: 0.7, format: "%.2f"),
                .init(key: "length", label: "Length", min: 0.0, max: 1.0, def: 0.45, format: "%.2f"),
                .init(key: "intensity", label: "Intensity", min: 0.0, max: 3.0, def: 1.2, format: "%.1f"),
            ]
        ),
        EffectDef(
            id: "starburst_spike",
            name: "Starburst",
            category: "Light",
            description: "Star diffraction spikes on bright light sources",
            params: [
                .init(key: "threshold", label: "Threshold", min: 0.3, max: 1.0, def: 0.65, format: "%.2f"),
                .init(key: "length", label: "Length", min: 0.05, max: 0.6, def: 0.25, format: "%.2f"),
                .init(key: "rays", label: "Rays", min: 4.0, max: 12.0, def: 6.0, format: "%.0f"),
            ]
        ),
        EffectDef(
            id: "god_rays",
            name: "God Rays",
            category: "Light",
            description: "Volumetric crepuscular light shafts from highlights",
            params: [
                .init(key: "intensity", label: "Intensity", min: 0.0, max: 2.0, def: 2.2, format: "%.1f"),
                .init(key: "decay", label: "Decay", min: 0.7, max: 1.0, def: 0.94, format: "%.2f"),
                .init(key: "cx", label: "Source X", min: 0.0, max: 1.0, def: 0.5, format: "%.2f"),
                .init(key: "cy", label: "Source Y", min: 0.0, max: 1.0, def: 0.85, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "aurora_borealis",
            name: "Aurora",
            category: "Light",
            description: "Animated aurora borealis color curtains",
            params: [
                .init(key: "intensity", label: "Intensity", min: 0.0, max: 2.0, def: 0.7, format: "%.1f"),
                .init(key: "speed", label: "Speed", min: 0.0, max: 2.0, def: 0.4, format: "%.1f"),
                .init(key: "color_shift", label: "Color Shift", min: 0.0, max: 1.0, def: 0.3, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "bokeh_dream",
            name: "Bokeh Dream",
            category: "Light",
            description: "Out-of-focus dreamy bokeh highlight circles",
            params: [
                .init(key: "radius", label: "Radius", min: 0.0, max: 0.08, def: 0.025, format: "%.3f"),
                .init(key: "threshold", label: "Threshold", min: 0.0, max: 1.0, def: 0.55, format: "%.2f"),
                .init(key: "intensity", label: "Intensity", min: 0.0, max: 4.0, def: 1.5, format: "%.1f"),
            ]
        ),
        EffectDef(
            id: "prism_disperse",
            name: "Prism",
            category: "Light",
            description: "Prismatic rainbow dispersion at edges",
            params: [
                .init(key: "spread", label: "Spread", min: 0.0, max: 0.2, def: 0.06, format: "%.2f"),
                .init(key: "intensity", label: "Intensity", min: 0.0, max: 2.0, def: 1.0, format: "%.1f"),
            ]
        ),
        EffectDef(
            id: "film_burn",
            name: "Film Burn",
            category: "Film",
            description: "Organic burning film edge degradation",
            params: [
                .init(key: "intensity", label: "Intensity", min: 0.0, max: 2.0, def: 0.8, format: "%.1f"),
                .init(key: "speed", label: "Speed", min: 0.0, max: 3.0, def: 1.2, format: "%.1f"),
                .init(key: "edge", label: "Edge", min: 0.0, max: 0.6, def: 0.25, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "oil_paint",
            name: "Oil Paint",
            category: "Art",
            description: "Kuwahara painterly filter — sharp but smooth like oil",
            params: [
                .init(key: "radius", label: "Brush", min: 2.0, max: 8.0, def: 4.0, format: "%.0f"),
                .init(key: "sharpness", label: "Sharpness", min: 0.0, max: 15.0, def: 6.0, format: "%.0f"),
            ]
        ),
        EffectDef(
            id: "stained_glass",
            name: "Stained Glass",
            category: "Art",
            description: "Voronoi-cell stained glass with dark lead borders",
            params: [
                .init(key: "cell_size", label: "Cell Size", min: 4.0, max: 48.0, def: 18.0, format: "%.0f"),
                .init(key: "border", label: "Border", min: 0.0, max: 0.3, def: 0.08, format: "%.2f"),
                .init(key: "saturation", label: "Saturation", min: 0.5, max: 3.0, def: 1.6, format: "%.1f"),
            ]
        ),
        EffectDef(
            id: "neon_edge_glow",
            name: "Neon Edges",
            category: "Light",
            description: "Sobel edge detection with colored neon glow",
            params: [
                .init(key: "threshold", label: "Threshold", min: 0.0, max: 0.5, def: 0.15, format: "%.2f"),
                .init(key: "glow", label: "Glow", min: 0.2, max: 2.0, def: 0.8, format: "%.1f"),
                .init(key: "hue", label: "Hue", min: 0.0, max: 1.0, def: 0.55, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "cyberpunk_grade",
            name: "Cyberpunk",
            category: "Color",
            description: "Deep blue-teal shadows with cyan/orange highlights",
            params: [
                .init(key: "shadow_teal", label: "Shadow Teal", min: 0.0, max: 1.0, def: 0.9, format: "%.1f"),
                .init(key: "hi_orange", label: "Hi Orange", min: 0.0, max: 1.0, def: 0.85, format: "%.1f"),
                .init(key: "contrast", label: "Contrast", min: 1.0, max: 2.5, def: 1.7, format: "%.1f"),
            ]
        ),
        EffectDef(
            id: "matrix_rain",
            name: "Matrix",
            category: "Pattern",
            description: "Digital matrix green rain overlay",
            params: [
                .init(key: "density", label: "Density", min: 0.0, max: 1.0, def: 0.45, format: "%.2f"),
                .init(key: "speed", label: "Speed", min: 0.5, max: 6.0, def: 2.0, format: "%.1f"),
                .init(key: "green_mix", label: "Mix", min: 0.0, max: 1.0, def: 0.55, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "pixel_sort",
            name: "Pixel Sort",
            category: "Glitch",
            description: "Glitch art: sorts pixels by brightness along rows",
            params: [
                .init(key: "threshold", label: "Threshold", min: 0.0, max: 0.9, def: 0.35, format: "%.2f"),
                .init(key: "intensity", label: "Intensity", min: 0.0, max: 1.0, def: 0.7, format: "%.2f"),
                .init(key: "direction", label: "Direction", min: 0.0, max: 1.0, def: 0.0, format: "%.0f"),
            ]
        ),
        EffectDef(
            id: "solarize",
            name: "Solarize",
            category: "Color",
            description: "Sabattier partial-negative solarization",
            params: [
                .init(key: "threshold", label: "Threshold", min: 0.0, max: 1.0, def: 0.5, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "double_ghost",
            name: "Double Ghost",
            category: "Glitch",
            description: "Double-exposure ghost offset — drunk / split double-vision",
            params: [
                .init(key: "offset", label: "Offset", min: 0.0, max: 0.15, def: 0.06, format: "%.3f"),
                .init(key: "opacity", label: "Opacity", min: 0.0, max: 1.0, def: 0.65, format: "%.2f"),
                .init(key: "angle", label: "Angle", min: 0.0, max: 90.0, def: 10.0, format: "%.0f"),
            ]
        ),
        EffectDef(
            id: "watercolor",
            name: "Watercolor",
            category: "Art",
            description: "Watercolor wash — bleeding edges and soft paper texture",
            params: [
                .init(key: "bleeding", label: "Bleeding", min: 0.003, max: 0.05, def: 0.018, format: "%.3f"),
                .init(key: "paper", label: "Paper", min: 0.0, max: 1.0, def: 0.5, format: "%.2f"),
                .init(key: "saturation", label: "Saturation", min: 0.8, max: 2.5, def: 1.4, format: "%.1f"),
            ]
        ),
        EffectDef(
            id: "comic_dots",
            name: "Comic Book",
            category: "Pattern",
            description: "Ben-Day halftone dots + ink outline like pop art comics",
            params: [
                .init(key: "dot_size", label: "Dot Size", min: 1.0, max: 10.0, def: 4.0, format: "%.0f"),
                .init(key: "ink_threshold", label: "Ink", min: 0.0, max: 0.4, def: 0.12, format: "%.2f"),
                .init(key: "color_levels", label: "Colors", min: 2.0, max: 8.0, def: 4.0, format: "%.0f"),
            ]
        ),
        EffectDef(
            id: "crosshatch",
            name: "Crosshatch",
            category: "Pattern",
            description: "Pen crosshatch shading on light sketch paper",
            params: [
                .init(key: "density", label: "Density", min: 2.0, max: 20.0, def: 6.0, format: "%.0f"),
                .init(key: "thickness", label: "Thickness", min: 0.15, max: 0.8, def: 0.5, format: "%.2f"),
                .init(key: "angle", label: "Angle", min: 0.0, max: 90.0, def: 0.0, format: "%.0f"),
            ]
        ),
        EffectDef(
            id: "daguerreotype",
            name: "Daguerreotype",
            category: "Film",
            description: "19th-century silver-plate sepia photograph",
            params: [
                .init(key: "tone", label: "Tone", min: 0.0, max: 1.0, def: 0.5, format: "%.2f"),
                .init(key: "vignette", label: "Vignette", min: 0.1, max: 2.0, def: 0.8, format: "%.1f"),
                .init(key: "scratch", label: "Scratch", min: 0.02, max: 1.0, def: 0.3, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "super8_film",
            name: "Super 8",
            category: "Film",
            description: "Super 8mm film with gate weave, grain and warm fade",
            params: [
                .init(key: "grain", label: "Grain", min: 0.05, max: 1.5, def: 0.5, format: "%.1f"),
                .init(key: "gate", label: "Gate Weave", min: 0.0, max: 1.0, def: 0.4, format: "%.2f"),
                .init(key: "fade", label: "Fade", min: 0.0, max: 1.0, def: 0.5, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "vhs_dropout",
            name: "VHS Dropout",
            category: "Glitch",
            description: "VHS tape dropout: horizontal signal-loss white bars",
            params: [
                .init(key: "density", label: "Density", min: 0.0, max: 0.4, def: 0.12, format: "%.2f"),
                .init(key: "speed", label: "Speed", min: 0.0, max: 8.0, def: 3.0, format: "%.1f"),
            ]
        ),
        EffectDef(
            id: "x_ray",
            name: "X-Ray",
            category: "Color",
            description: "X-ray: inverted high-contrast with blue-white tone",
            params: [
                .init(key: "contrast", label: "Contrast", min: 0.5, max: 4.0, def: 1.8, format: "%.1f"),
                .init(key: "blue_tint", label: "Blue Tint", min: 0.0, max: 1.0, def: 0.6, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "bit_crush",
            name: "Bit Crush",
            category: "Glitch",
            description: "Bit-depth reduction — chunky posterized pixels with dither",
            params: [
                .init(key: "levels", label: "Levels", min: 2.0, max: 16.0, def: 5.0, format: "%.0f"),
                .init(key: "dither", label: "Dither", min: 0.0, max: 1.0, def: 0.4, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "tv_static",
            name: "TV Static",
            category: "Glitch",
            description: "Analog TV static noise — channel between stations",
            params: [
                .init(key: "intensity", label: "Intensity", min: 0.0, max: 1.0, def: 0.55, format: "%.2f"),
                .init(key: "color_mix", label: "Color Mix", min: 0.0, max: 1.0, def: 0.25, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "dither_bayer",
            name: "Dither",
            category: "Glitch",
            description: "Ordered Bayer dithering — retro 1-bit style",
            params: [
                .init(key: "levels", label: "Levels", min: 1.0, max: 8.0, def: 3.0, format: "%.0f"),
                .init(key: "scale", label: "Scale", min: 1.0, max: 6.0, def: 2.0, format: "%.0f"),
                .init(key: "color", label: "Color", min: 0.0, max: 1.0, def: 0.4, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "miami_vice",
            name: "Miami Vice",
            category: "Color",
            description: "80s hot pink and teal pastel neon palette",
            params: [
                .init(key: "saturation", label: "Saturation", min: 0.5, max: 3.0, def: 1.8, format: "%.1f"),
            ]
        ),
        EffectDef(
            id: "horror_grade",
            name: "Horror",
            category: "Color",
            description: "Desaturated red-channel horror film grade",
            params: [
                .init(key: "desat", label: "Desaturate", min: 0.0, max: 1.0, def: 0.8, format: "%.2f"),
                .init(key: "red", label: "Red Boost", min: 0.0, max: 1.0, def: 0.45, format: "%.2f"),
                .init(key: "crush", label: "Crush", min: 0.0, max: 0.4, def: 0.15, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "split_toning",
            name: "Split Tone",
            category: "Color",
            description: "Shadow/highlight split toning with independent hue control",
            params: [
                .init(key: "shadow_hue", label: "Shadow Hue", min: 0.0, max: 1.0, def: 0.6, format: "%.2f"),
                .init(key: "hi_hue", label: "Highlight Hue", min: 0.0, max: 1.0, def: 0.1, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "desert_gold",
            name: "Desert Gold",
            category: "Color",
            description: "Sun-bleached golden desert haze with lifted blacks",
            params: [
                .init(key: "warmth", label: "Warmth", min: 0.1, max: 1.0, def: 0.7, format: "%.2f"),
                .init(key: "fade", label: "Fade", min: 0.0, max: 1.0, def: 0.6, format: "%.2f"),
                .init(key: "haze", label: "Haze", min: 0.0, max: 1.0, def: 0.5, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "emboss_relief",
            name: "Emboss",
            category: "Art",
            description: "3D emboss relief sculpture with directional lighting",
            params: [
                .init(key: "angle", label: "Light Angle", min: 0.0, max: 360.0, def: 135.0, format: "%.0f"),
                .init(key: "colorize", label: "Colorize", min: 0.0, max: 1.0, def: 0.0, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "pointillist",
            name: "Pointillism",
            category: "Art",
            description: "Seurat-style pointillist dots — image from colored circles",
            params: [
                .init(key: "dot_size", label: "Dot Size", min: 2.0, max: 14.0, def: 5.0, format: "%.0f"),
                .init(key: "scatter", label: "Scatter", min: 0.0, max: 1.0, def: 0.4, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "interlace_glitch",
            name: "Interlace",
            category: "Glitch",
            description: "CRT interlace field offset glitch — alternating row shift",
            params: [
                .init(key: "intensity", label: "Intensity", min: 0.0, max: 1.0, def: 0.6, format: "%.2f"),
                .init(key: "speed", label: "Speed", min: 0.0, max: 6.0, def: 2.0, format: "%.1f"),
            ]
        ),
        EffectDef(
            id: "frosted_glass",
            name: "Frosted Glass",
            category: "Warp",
            description: "Frosted glass — directional blur with edge-dependent scatter",
            params: [
                .init(key: "blur", label: "Blur", min: 0.003, max: 0.05, def: 0.018, format: "%.3f"),
                .init(key: "noise", label: "Noise", min: 0.0, max: 1.0, def: 0.4, format: "%.2f"),
                .init(key: "tint", label: "Tint", min: 0.0, max: 1.0, def: 0.3, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "mirror_fold",
            name: "Mirror Fold",
            category: "Warp",
            description: "Horizontal mirror fold — left half reflects to right",
            params: [
                .init(key: "axis", label: "Axis", min: 0.0, max: 1.0, def: 0.5, format: "%.2f"),
                .init(key: "vertical", label: "Vertical", min: 0.0, max: 1.0, def: 0.0, format: "%.0f"),
            ]
        ),
        EffectDef(
            id: "echo_trails",
            name: "Echo Trails",
            category: "Motion",
            description: "Fading ghost trail echo copies shifted in a direction",
            params: [
                .init(key: "offset", label: "Offset", min: 0.005, max: 0.1, def: 0.025, format: "%.3f"),
                .init(key: "fade", label: "Fade", min: 0.1, max: 0.9, def: 0.55, format: "%.2f"),
                .init(key: "angle", label: "Angle", min: 0.0, max: 360.0, def: 45.0, format: "%.0f"),
            ]
        ),
        EffectDef(
            id: "gradient_map",
            name: "Gradient Map",
            category: "Color",
            description: "Maps luminance to a two-color gradient ramp",
            params: [
                .init(key: "hue1", label: "Shadow Hue", min: 0.0, max: 1.0, def: 0.65, format: "%.2f"),
                .init(key: "hue2", label: "Highlight Hue", min: 0.0, max: 1.0, def: 0.12, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "cross_process",
            name: "Cross Process",
            category: "Color",
            description: "E6 slide film cross-processed in C41: wild hue shifts",
            params: [
                .init(key: "contrast", label: "Contrast", min: 1.0, max: 2.5, def: 1.4, format: "%.1f"),
            ]
        ),
        EffectDef(
            id: "plasma_field",
            name: "Plasma",
            category: "Pattern",
            description: "Psychedelic animated plasma color field overlay",
            params: [
                .init(key: "scale", label: "Scale", min: 1.0, max: 12.0, def: 4.0, format: "%.0f"),
                .init(key: "speed", label: "Speed", min: 0.0, max: 5.0, def: 1.5, format: "%.1f"),
                .init(key: "intensity", label: "Mix", min: 0.0, max: 1.0, def: 0.55, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "fire_edge",
            name: "Fire Edge",
            category: "Light",
            description: "Procedural fire rises from the bottom edges",
            params: [
                .init(key: "intensity", label: "Intensity", min: 0.0, max: 2.5, def: 1.5, format: "%.1f"),
                .init(key: "speed", label: "Speed", min: 0.0, max: 5.0, def: 2.0, format: "%.1f"),
                .init(key: "height", label: "Height", min: 0.0, max: 1.0, def: 0.25, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "laser_grid",
            name: "Laser Grid",
            category: "Pattern",
            description: "Sci-fi laser wireframe grid overlay",
            params: [
                .init(key: "grid_size", label: "Grid Size", min: 4.0, max: 40.0, def: 14.0, format: "%.0f"),
                .init(key: "hue", label: "Hue", min: 0.0, max: 1.0, def: 0.5, format: "%.2f"),
                .init(key: "intensity", label: "Intensity", min: 0.0, max: 2.0, def: 0.8, format: "%.1f"),
            ]
        ),
        EffectDef(
            id: "technicolor",
            name: "Technicolor",
            category: "Color",
            description: "3-strip Technicolor: vivid saturated film-era color",
            params: [
                .init(key: "saturation", label: "Saturation", min: 1.0, max: 4.0, def: 2.0, format: "%.1f"),
                .init(key: "contrast", label: "Contrast", min: 1.0, max: 2.5, def: 1.3, format: "%.1f"),
                .init(key: "warmth", label: "Warmth", min: 0.0, max: 1.0, def: 0.35, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "ice_crystal",
            name: "Ice Crystal",
            category: "Light",
            description: "Crystalline ice-fracture distortion pattern",
            params: [
                .init(key: "scale", label: "Scale", min: 2.0, max: 20.0, def: 8.0, format: "%.0f"),
                .init(key: "refract", label: "Refract", min: 0.01, max: 0.15, def: 0.04, format: "%.3f"),
                .init(key: "tint", label: "Blue Tint", min: 0.0, max: 1.0, def: 0.35, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "kodachrome",
            name: "Kodachrome",
            category: "Color",
            description: "Kodachrome 64 film — deep reds, rich saturation, golden shadows",
            params: [
                .init(key: "saturation", label: "Saturation", min: 0.8, max: 3.0, def: 1.5, format: "%.1f"),
                .init(key: "reds", label: "Red Boost", min: 0.0, max: 1.0, def: 0.5, format: "%.2f"),
                .init(key: "shadows", label: "Gold Shadow", min: 0.0, max: 1.0, def: 0.4, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "vortex_distort",
            name: "Vortex",
            category: "Warp",
            description: "Multi-vortex turbulent distortion field",
            params: [
                .init(key: "scale", label: "Scale", min: 1.0, max: 8.0, def: 3.0, format: "%.0f"),
                .init(key: "speed", label: "Speed", min: 0.0, max: 3.0, def: 0.8, format: "%.1f"),
            ]
        ),
        EffectDef(
            id: "sepia_rich",
            name: "Sepia",
            category: "Color",
            description: "Rich warm sepia with crushed blacks and vignette",
            params: [
                .init(key: "vignette", label: "Vignette", min: 0.0, max: 2.0, def: 0.7, format: "%.1f"),
                .init(key: "contrast", label: "Contrast", min: 0.5, max: 2.0, def: 1.2, format: "%.1f"),
            ]
        ),
        EffectDef(
            id: "digital_noise",
            name: "Digital Noise",
            category: "Glitch",
            description: "Colored RGB pixel noise — digital sensor ISO noise",
            params: [
                .init(key: "intensity", label: "Intensity", min: 0.0, max: 1.0, def: 0.5, format: "%.2f"),
                .init(key: "color_sep", label: "Color Sep", min: 0.0, max: 1.0, def: 0.7, format: "%.2f"),
                .init(key: "luma_bias", label: "Luma Bias", min: 0.0, max: 1.0, def: 0.5, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "color_dodge",
            name: "Color Dodge",
            category: "Color",
            description: "Photographic color dodge — luminous blown-out look",
            params: [
                .init(key: "intensity", label: "Intensity", min: 0.0, max: 1.0, def: 0.5, format: "%.2f"),
                .init(key: "hue", label: "Dodge Hue", min: 0.0, max: 1.0, def: 0.08, format: "%.2f"),
                .init(key: "glow", label: "Glow", min: 0.0, max: 1.0, def: 0.6, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "warhol_pop",
            name: "Pop Art",
            category: "Art",
            description: "Andy Warhol pop art — bold flat posterized colors",
            params: [
                .init(key: "levels", label: "Levels", min: 2.0, max: 8.0, def: 4.0, format: "%.0f"),
                .init(key: "hue_shift", label: "Hue Shift", min: 0.0, max: 1.0, def: 0.25, format: "%.2f"),
                .init(key: "saturation", label: "Saturation", min: 1.0, max: 4.0, def: 2.5, format: "%.1f"),
            ]
        ),
        EffectDef(
            id: "infrared_film",
            name: "Infrared",
            category: "Color",
            description: "Infrared film: glowing white foliage, dark skies",
            params: [
                .init(key: "channel_mix", label: "IR Mix", min: 0.0, max: 1.0, def: 0.8, format: "%.2f"),
                .init(key: "glow", label: "Glow", min: 0.05, max: 1.0, def: 0.4, format: "%.2f"),
                .init(key: "contrast", label: "Contrast", min: 0.5, max: 3.0, def: 1.4, format: "%.1f"),
            ]
        ),
        EffectDef(
            id: "scanline_color",
            name: "RGB Scanlines",
            category: "Glitch",
            description: "RGB phosphor triad scanlines — arcade monitor look",
            params: [
                .init(key: "line_width", label: "Line Width", min: 1.0, max: 6.0, def: 3.0, format: "%.0f"),
                .init(key: "intensity", label: "Intensity", min: 0.0, max: 1.0, def: 0.7, format: "%.2f"),
                .init(key: "rgb_sep", label: "RGB Sep", min: 0.0, max: 1.0, def: 0.5, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "data_corrupt",
            name: "Data Corrupt",
            category: "Glitch",
            description: "Data corruption: random color block replacements",
            params: [
                .init(key: "density", label: "Density", min: 0.0, max: 0.5, def: 0.18, format: "%.2f"),
                .init(key: "block_size", label: "Block Size", min: 2.0, max: 24.0, def: 8.0, format: "%.0f"),
                .init(key: "intensity", label: "Intensity", min: 0.0, max: 1.0, def: 0.9, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "long_exposure",
            name: "Long Exposure",
            category: "Motion",
            description: "Simulated long exposure — trails of light brighten",
            params: [
                .init(key: "threshold", label: "Threshold", min: 0.0, max: 1.0, def: 0.35, format: "%.2f"),
                .init(key: "trail", label: "Trail", min: 0.01, max: 0.2, def: 0.06, format: "%.2f"),
                .init(key: "glow", label: "Glow", min: 0.1, max: 2.0, def: 1.0, format: "%.1f"),
            ]
        ),
        EffectDef(
            id: "pixel_mosaic",
            name: "Pixel Mosaic",
            category: "Glitch",
            description: "Large pixel blocks with quantized colors",
            params: [
                .init(key: "block_size", label: "Block Size", min: 2.0, max: 64.0, def: 16.0, format: "%.0f"),
                .init(key: "color_steps", label: "Color Steps", min: 2.0, max: 16.0, def: 6.0, format: "%.0f"),
            ]
        ),
        EffectDef(
            id: "thermal_map",
            name: "Thermal Camera",
            category: "Color",
            description: "Infrared thermal camera heat palette",
            params: [
                .init(key: "cold_hue", label: "Cold Hue", min: 0.0, max: 1.0, def: 0.65, format: "%.2f"),
                .init(key: "hot_hue", label: "Hot Hue", min: 0.0, max: 1.0, def: 0.08, format: "%.2f"),
                .init(key: "contrast", label: "Contrast", min: 0.8, max: 3.0, def: 1.4, format: "%.2f"),
                .init(key: "scanlines", label: "Scanlines", min: 0.0, max: 1.0, def: 0.15, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "tilt_shift",
            name: "Tilt-Shift Miniature",
            category: "Warp",
            description: "Miniature tilt-shift focus blur",
            params: [
                .init(key: "focus_y", label: "Focus Center", min: 0.0, max: 1.0, def: 0.5, format: "%.2f"),
                .init(key: "focus_band", label: "Focus Band", min: 0.02, max: 0.5, def: 0.08, format: "%.3f"),
                .init(key: "blur_radius", label: "Blur Radius", min: 2.0, max: 30.0, def: 12.0, format: "%.1f"),
                .init(key: "saturation", label: "Saturation", min: 1.0, max: 3.0, def: 1.8, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "raindrop_refract",
            name: "Raindrops",
            category: "Warp",
            description: "Animated raindrop lens refraction",
            params: [
                .init(key: "density", label: "Density", min: 1.0, max: 20.0, def: 8.0, format: "%.1f"),
                .init(key: "size", label: "Size", min: 0.1, max: 1.0, def: 0.45, format: "%.2f"),
                .init(key: "refract_str", label: "Refraction", min: 0.1, max: 2.0, def: 1.2, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "risograph",
            name: "Risograph Print",
            category: "Art",
            description: "2-ink halftone risograph printing",
            params: [
                .init(key: "hue1", label: "Ink 1 Hue", min: 0.0, max: 1.0, def: 0.58, format: "%.2f"),
                .init(key: "hue2", label: "Ink 2 Hue", min: 0.0, max: 1.0, def: 0.02, format: "%.2f"),
                .init(key: "dot_size", label: "Dot Size", min: 1.0, max: 8.0, def: 3.0, format: "%.1f"),
                .init(key: "misreg", label: "Mis-register", min: 0.0, max: 0.02, def: 0.004, format: "%.3f"),
                .init(key: "paper", label: "Paper Tone", min: 0.0, max: 1.0, def: 0.9, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "vintage_negative",
            name: "Vintage Negative",
            category: "Film",
            description: "Inverted orange-mask film negative",
            params: [
                .init(key: "orange_mask", label: "Orange Mask", min: 0.0, max: 1.0, def: 0.55, format: "%.2f"),
                .init(key: "contrast", label: "Contrast", min: 0.5, max: 2.5, def: 1.3, format: "%.2f"),
                .init(key: "grain", label: "Grain", min: 0.0, max: 1.0, def: 0.12, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "pencil_sketch",
            name: "Pencil Sketch",
            category: "Art",
            description: "Pencil sketch with cross-hatching",
            params: [
                .init(key: "line_str", label: "Line Strength", min: 0.5, max: 5.0, def: 2.5, format: "%.1f"),
                .init(key: "paper_tone", label: "Paper Tone", min: 0.7, max: 1.0, def: 0.95, format: "%.3f"),
                .init(key: "hatching", label: "Hatching", min: 0.0, max: 1.0, def: 0.4, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "crt_barrel",
            name: "CRT Barrel",
            category: "Pattern",
            description: "CRT barrel distortion with scanlines",
            params: [
                .init(key: "distort", label: "Distortion", min: 0.0, max: 1.0, def: 0.35, format: "%.2f"),
                .init(key: "corner_dark", label: "Corner Dark", min: 0.0, max: 3.0, def: 1.8, format: "%.2f"),
                .init(key: "rgb_shift", label: "RGB Shift", min: 0.0, max: 0.02, def: 0.004, format: "%.4f"),
                .init(key: "scanline", label: "Scanlines", min: 0.0, max: 1.0, def: 0.35, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "rgb_split_wave",
            name: "RGB Wave Split",
            category: "Glitch",
            description: "Per-channel sine wave RGB split",
            params: [
                .init(key: "amplitude", label: "Amplitude", min: 0.003, max: 0.05, def: 0.018, format: "%.3f"),
                .init(key: "frequency", label: "Frequency", min: 1.0, max: 20.0, def: 6.0, format: "%.1f"),
                .init(key: "speed", label: "Speed", min: 0.0, max: 10.0, def: 2.5, format: "%.1f"),
            ]
        ),
        EffectDef(
            id: "golden_hour",
            name: "Golden Hour",
            category: "Color",
            description: "Warm sunset golden hour grade",
            params: [
                .init(key: "warmth", label: "Warmth", min: 0.1, max: 1.0, def: 0.8, format: "%.2f"),
                .init(key: "glow_str", label: "Glow", min: 0.1, max: 1.0, def: 0.7, format: "%.2f"),
                .init(key: "shadow_lift", label: "Shadow Lift", min: 0.0, max: 0.3, def: 0.15, format: "%.3f"),
                .init(key: "vignette", label: "Vignette", min: 0.1, max: 2.0, def: 0.5, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "neon_sign",
            name: "Neon Sign",
            category: "Light",
            description: "Edge-detected neon glow tubes",
            params: [
                .init(key: "edge_str", label: "Edge Strength", min: 1.0, max: 10.0, def: 4.0, format: "%.1f"),
                .init(key: "glow_radius", label: "Glow Radius", min: 2.0, max: 20.0, def: 8.0, format: "%.1f"),
                .init(key: "hue_shift", label: "Hue Shift", min: 0.0, max: 1.0, def: 0.0, format: "%.2f"),
                .init(key: "bg_darken", label: "BG Darken", min: 0.0, max: 1.0, def: 0.75, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "mirror_tunnel",
            name: "Mirror Tunnel",
            category: "Warp",
            description: "Infinite mirror tunnel vortex",
            params: [
                .init(key: "depth", label: "Depth", min: 2.0, max: 12.0, def: 5.0, format: "%.1f"),
                .init(key: "rotation", label: "Rotation", min: 0.0, max: 1.0, def: 0.12, format: "%.2f"),
                .init(key: "zoom", label: "Zoom", min: 0.3, max: 0.95, def: 0.65, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "liquid_chrome",
            name: "Liquid Chrome",
            category: "Warp",
            description: "Animated liquid metallic chrome",
            params: [
                .init(key: "flow", label: "Flow", min: 0.1, max: 1.0, def: 0.5, format: "%.2f"),
                .init(key: "metallic", label: "Metallic", min: 0.1, max: 1.0, def: 0.7, format: "%.2f"),
                .init(key: "tint_r", label: "Tint R", min: 0.0, max: 1.0, def: 0.85, format: "%.2f"),
                .init(key: "tint_g", label: "Tint G", min: 0.0, max: 1.0, def: 0.9, format: "%.2f"),
                .init(key: "tint_b", label: "Tint B", min: 0.0, max: 1.0, def: 1.0, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "zone_system_bw",
            name: "Zone System B&W",
            category: "Color",
            description: "Zone system B&W with film grain",
            params: [
                .init(key: "zones", label: "Zones", min: 3.0, max: 10.0, def: 6.0, format: "%.0f"),
                .init(key: "contrast", label: "Contrast", min: 0.8, max: 3.0, def: 1.6, format: "%.2f"),
                .init(key: "grain", label: "Grain", min: 0.0, max: 1.0, def: 0.08, format: "%.2f"),
                .init(key: "paper_white", label: "Paper White", min: 0.85, max: 1.0, def: 0.96, format: "%.3f"),
            ]
        ),
        EffectDef(
            id: "glitter_dust",
            name: "Glitter Dust",
            category: "Light",
            description: "Animated sparkle glitter overlay",
            params: [
                .init(key: "density", label: "Density", min: 100.0, max: 2000.0, def: 800.0, format: "%.0f"),
                .init(key: "size", label: "Size", min: 0.2, max: 2.0, def: 0.8, format: "%.1f"),
                .init(key: "sparkle", label: "Sparkle", min: 0.2, max: 2.0, def: 1.0, format: "%.2f"),
                .init(key: "color_var", label: "Color Var", min: 0.0, max: 1.0, def: 1.0, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "contour_map",
            name: "Contour Map",
            category: "Pattern",
            description: "Topographic contour line overlay",
            params: [
                .init(key: "levels", label: "Levels", min: 3.0, max: 20.0, def: 8.0, format: "%.0f"),
                .init(key: "line_width", label: "Line Width", min: 0.01, max: 0.15, def: 0.04, format: "%.3f"),
                .init(key: "line_hue", label: "Line Hue", min: 0.0, max: 1.0, def: 0.35, format: "%.2f"),
                .init(key: "fill_sat", label: "Fill Sat", min: 0.0, max: 1.0, def: 0.6, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "film_halation",
            name: "Film Halation",
            category: "Film",
            description: "Red-orange bloom from bright highlights",
            params: [
                .init(key: "threshold", label: "Threshold", min: 0.3, max: 0.9, def: 0.3, format: "%.2f"),
                .init(key: "radius", label: "Radius", min: 2.0, max: 20.0, def: 16.0, format: "%.1f"),
                .init(key: "red_shift", label: "Red Shift", min: 0.0, max: 1.0, def: 0.75, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "ascii_art",
            name: "ASCII Art",
            category: "Pattern",
            description: "ASCII character density rendering",
            params: [
                .init(key: "char_size", label: "Char Size", min: 4.0, max: 24.0, def: 10.0, format: "%.0f"),
                .init(key: "fg_r", label: "FG Red", min: 0.0, max: 1.0, def: 0.0, format: "%.2f"),
                .init(key: "fg_g", label: "FG Green", min: 0.0, max: 1.0, def: 1.0, format: "%.2f"),
                .init(key: "fg_b", label: "FG Blue", min: 0.0, max: 1.0, def: 0.15, format: "%.2f"),
                .init(key: "bg_dark", label: "BG Darken", min: 0.0, max: 1.0, def: 0.85, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "dna_helix",
            name: "DNA Helix Grid",
            category: "Pattern",
            description: "Animated DNA helix wire overlay",
            params: [
                .init(key: "grid_scale", label: "Grid Scale", min: 5.0, max: 30.0, def: 12.0, format: "%.1f"),
                .init(key: "wave_amp", label: "Wave Amp", min: 0.15, max: 1.0, def: 0.5, format: "%.2f"),
                .init(key: "line_width", label: "Line Width", min: 0.02, max: 0.15, def: 0.05, format: "%.3f"),
                .init(key: "hue", label: "Hue", min: 0.0, max: 1.0, def: 0.55, format: "%.2f"),
                .init(key: "bg_darken", label: "BG Darken", min: 0.0, max: 1.0, def: 0.6, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "double_exposure",
            name: "Double Exposure",
            category: "Film",
            description: "Screen-blended double exposure",
            params: [
                .init(key: "offset_x", label: "Offset X", min: -0.3, max: 0.3, def: 0.15, format: "%.3f"),
                .init(key: "offset_y", label: "Offset Y", min: -0.3, max: 0.3, def: -0.1, format: "%.3f"),
                .init(key: "scale2", label: "Scale 2", min: 0.5, max: 2.0, def: 1.15, format: "%.2f"),
                .init(key: "desaturate2", label: "Desaturate 2", min: 0.0, max: 1.0, def: 0.6, format: "%.2f"),
                .init(key: "opacity", label: "Opacity", min: 0.0, max: 1.0, def: 0.8, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "ken_burns",
            name: "Ken Burns",
            category: "Motion",
            description: "Animated zoom & pan — push in or pull back across the clip duration",
            params: [
                .init(key: "start_scale", label: "Start Scale", min: 0.5, max: 4.0, def: 1.0, format: "%.2f×"),
                .init(key: "end_scale", label: "End Scale", min: 0.5, max: 4.0, def: 1.3, format: "%.2f×"),
                .init(key: "start_x", label: "Start X", min: 0.0, max: 1.0, def: 0.5, format: "%.2f"),
                .init(key: "start_y", label: "Start Y", min: 0.0, max: 1.0, def: 0.5, format: "%.2f"),
                .init(key: "end_x", label: "End X", min: 0.0, max: 1.0, def: 0.5, format: "%.2f"),
                .init(key: "end_y", label: "End Y", min: 0.0, max: 1.0, def: 0.5, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "skin_smooth",
            name: "Skin Smooth",
            category: "Beauty",
            description: "Beauty smoothing  ·  edge-preserving, skin-tone gated  ·  pores soften, jawlines don't",
            params: [
                .init(key: "radius", label: "Smoothness", min: 1.0, max: 6.0, def: 3.0, format: "%.1f px"),
                .init(key: "tone", label: "Skin Range", min: 0.0, max: 1.0, def: 0.5, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "glow_up",
            name: "Glow Up",
            category: "Beauty",
            description: "Soft-focus portrait glow  ·  warmth + lift  ·  diffusion-filter look",
            params: [
                .init(key: "glow", label: "Glow", min: 0.0, max: 1.0, def: 0.5, format: "%.2f"),
                .init(key: "warmth", label: "Warmth", min: -1.0, max: 1.0, def: 0.25, format: "%.2f"),
                .init(key: "brighten", label: "Brighten", min: 0.0, max: 0.5, def: 0.15, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "cam_shake",
            name: "Cam Shake",
            category: "Motion",
            description: "Handheld camera shake  ·  continuous jitter + micro-zoom  ·  TikTok energy",
            params: [
                .init(key: "intensity", label: "Shake", min: 0.0, max: 1.0, def: 0.5, format: "%.2f"),
                .init(key: "speed", label: "Speed", min: 0.1, max: 4.0, def: 1.0, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "greenscreen",
            name: "Chroma Key",
            category: "Tools",
            description: "Clean colour keyer - green screen - keys a colour out so the track below shows through",
            params: [
                .init(key: "key_r", label: "Key R", min: 0.0, max: 1.0, def: 0.0, format: "%.2f"),
                .init(key: "key_g", label: "Key G", min: 0.0, max: 1.0, def: 1.0, format: "%.2f"),
                .init(key: "key_b", label: "Key B", min: 0.0, max: 1.0, def: 0.0, format: "%.2f"),
                .init(key: "similarity", label: "Similarity", min: 0.01, max: 1.0, def: 0.4, format: "%.2f"),
                .init(key: "smoothness", label: "Edge Softness", min: 0.0, max: 0.5, def: 0.08, format: "%.2f"),
                .init(key: "spill", label: "Spill Kill", min: 0.0, max: 1.0, def: 0.5, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "retro_beauty",
            name: "Retro Beauty",
            category: "Beauty",
            description: "2016 beauty-cam · diffusion glow, milky fade, warm-pink cast · pair with Skin Smooth",
            params: [
                .init(key: "glow", label: "Glow", min: 0.0, max: 1.0, def: 0.6, format: "%.2f"),
                .init(key: "fade", label: "Fade", min: 0.0, max: 1.0, def: 0.5, format: "%.2f"),
                .init(key: "blush", label: "Blush", min: 0.0, max: 1.0, def: 0.35, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "insta_2016",
            name: "2016",
            category: "Color",
            description: "the 2016 feed grade · faded blacks, sat punch, warm mids over teal shadows, corner vignette",
            params: [
                .init(key: "fade", label: "Fade", min: 0.0, max: 1.0, def: 0.45, format: "%.2f"),
                .init(key: "pop", label: "Pop", min: 0.0, max: 1.0, def: 0.6, format: "%.2f"),
                .init(key: "warmth", label: "Warmth", min: -1.0, max: 1.0, def: 0.35, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "glass_skin",
            name: "Glass Skin",
            category: "Beauty",
            description: "modern K-beauty · chroma-gated smoothing + dewy wet-highlight sheen",
            params: [
                .init(key: "radius", label: "Smoothness", min: 1.0, max: 6.0, def: 3.5, format: "%.1f px"),
                .init(key: "gloss", label: "Gloss", min: 0.0, max: 1.0, def: 0.5, format: "%.2f"),
            ]
        ),
    ]

    // Audio effects (5) — engine vocabulary ids;
    // param keys match add_effect_brick / add_audio_multifx_brick.
    static let audio: [EffectDef] = [
        EffectDef(
            id: "audio_reverb",
            name: "Reverb",
            category: "Audio",
            description: "Freeverb-style room reverb — comb+allpass, size and damping",
            params: [
                .init(key: "room", label: "Room Size", min: 0.0, max: 1.0, def: 0.5, format: "%.2f"),
                .init(key: "damp", label: "Damping", min: 0.0, max: 1.0, def: 0.5, format: "%.2f"),
                .init(key: "mix", label: "Mix", min: 0.0, max: 1.0, def: 0.3, format: "%.2f"),
                .init(key: "dry_wet", label: "Dry/Wet", min: 0.0, max: 1.0, def: 1.0, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "audio_delay",
            name: "Delay",
            category: "Audio",
            description: "Echo delay — time, feedback and wet mix",
            params: [
                .init(key: "time", label: "Time", min: 0.01, max: 2.0, def: 0.3, format: "%.2f s"),
                .init(key: "feedback", label: "Feedback", min: 0.0, max: 0.95, def: 0.4, format: "%.2f"),
                .init(key: "mix", label: "Mix", min: 0.0, max: 1.0, def: 0.3, format: "%.2f"),
                .init(key: "dry_wet", label: "Dry/Wet", min: 0.0, max: 1.0, def: 1.0, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "audio_autotune",
            name: "Autotune",
            category: "Audio",
            description: "Pitch correction — YIN detection, hard snap to gentle glide",
            params: [
                .init(key: "speed_ms", label: "Speed", min: 0.0, max: 100.0, def: 0.0, format: "%.0f ms"),
                .init(key: "dry_wet", label: "Dry/Wet", min: 0.0, max: 1.0, def: 1.0, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "audio_pitch",
            name: "Pitch Shift",
            category: "Audio",
            description: "Fixed-ratio pitch shift in semitones, no detection",
            params: [
                .init(key: "semitones", label: "Semitones", min: -24.0, max: 24.0, def: 0.0, format: "%+.0f st"),
                .init(key: "dry_wet", label: "Dry/Wet", min: 0.0, max: 1.0, def: 1.0, format: "%.2f"),
            ]
        ),
        EffectDef(
            id: "audio_formant",
            name: "Formant",
            category: "Audio",
            description: "Formant shift — voice character, independent of pitch",
            params: [
                .init(key: "shift", label: "Shift", min: -1.0, max: 1.0, def: 0.0, format: "%+.2f"),
                .init(key: "dry_wet", label: "Dry/Wet", min: 0.0, max: 1.0, def: 1.0, format: "%.2f"),
            ]
        ),
    ]

    static let all: [EffectDef] = video + audio

    static let byID: [String: EffectDef] =
        Dictionary(uniqueKeysWithValues: all.map { ($0.id, $0) })

    // Unique video categories, first-appearance order.
    static let videoCategories: [String] = [
        "Glitch",
        "Film",
        "Pattern",
        "Color",
        "Light",
        "Warp",
        "Art",
        "Motion",
        "Beauty",
        "Tools",
    ]
}
