#!/usr/bin/env python3
"""Generate App/Sources/GeneratedEffectCatalog.swift — the effect catalog the
SwiftUI shell compiles against.

Sources (sibling checkout of the desktop repo, like tools/gen_levers.py):
  - effects/mcp_manifest.json     (video effects: params/ranges/defaults)
  - audio effects are NOT in the manifest; their engine vocabulary ids and
    param keys (what add_effect_brick / add_audio_multifx_brick read in
    src/ipc_server.cpp) plus ranges/defaults (src/audio_fx.h AudioFX) are
    encoded in AUDIO_EFFECTS below. If the engine grows a manifest for them,
    switch to it.

Regenerate:
  PMS_DESKTOP=../pop-maker-studio python3 tools/gen_effect_catalog.py

Output is deterministic: manifest order preserved, stable formatting.
"""
import json
import os

REPO_ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
ENGINE = os.environ.get("PMS_DESKTOP", os.path.join(REPO_ROOT, "..", "pop-maker-studio"))
OUT_PATH = os.path.join(REPO_ROOT, "App", "Sources", "GeneratedEffectCatalog.swift")

HEADER = """\
// GENERATED by tools/gen_effect_catalog.py — DO NOT EDIT
// Regenerate: PMS_DESKTOP=../pop-maker-studio python3 tools/gen_effect_catalog.py
//
// Video effects come from $PMS_DESKTOP/effects/mcp_manifest.json.
// Audio effects use engine vocabulary ids and the exact param keys read by
// the engine's add_effect_brick / add_audio_multifx_brick handlers
// (src/ipc_server.cpp); ranges/defaults from src/audio_fx.h (AudioFX).

import Foundation

struct EffectDef: Identifiable, Hashable {
    let id: String
    let name: String
    let category: String
    let description: String
    let params: [Param]
    struct Param: Hashable {
        let key: String
        let label: String
        let min: Double
        let max: Double
        let def: Double
        let format: String
    }
}
"""

# Audio effects — hand-authored (not in mcp_manifest.json).
# ids/param keys: engine vocabulary, verified against src/ipc_server.cpp
# (add_effect_brick / add_audio_multifx_brick). Ranges/defaults: the AudioFX
# struct in src/audio_fx.h. Every audio brick also honours "dry_wet"
# (brick-level blend, 1 = fully wet).
DRY_WET = ("dry_wet", "Dry/Wet", 0.0, 1.0, 1.0, "%.2f")
AUDIO_EFFECTS = [
    {
        "id": "audio_reverb",
        "label": "Reverb",
        "category": "Audio",
        "description": "Freeverb-style room reverb — comb+allpass, size and damping",
        "params": [
            ("room", "Room Size", 0.0, 1.0, 0.5, "%.2f"),
            ("damp", "Damping", 0.0, 1.0, 0.5, "%.2f"),
            ("mix", "Mix", 0.0, 1.0, 0.3, "%.2f"),
            DRY_WET,
        ],
    },
    {
        "id": "audio_delay",
        "label": "Delay",
        "category": "Audio",
        "description": "Echo delay — time, feedback and wet mix",
        "params": [
            ("time", "Time", 0.01, 2.0, 0.3, "%.2f s"),
            ("feedback", "Feedback", 0.0, 0.95, 0.4, "%.2f"),
            ("mix", "Mix", 0.0, 1.0, 0.3, "%.2f"),
            DRY_WET,
        ],
    },
    {
        "id": "audio_autotune",
        "label": "Autotune",
        "category": "Audio",
        "description": "Pitch correction — YIN detection, hard snap to gentle glide",
        "params": [
            ("speed_ms", "Speed", 0.0, 100.0, 0.0, "%.0f ms"),
            DRY_WET,
        ],
    },
    {
        "id": "audio_pitch",
        "label": "Pitch Shift",
        "category": "Audio",
        "description": "Fixed-ratio pitch shift in semitones, no detection",
        "params": [
            ("semitones", "Semitones", -24.0, 24.0, 0.0, "%+.0f st"),
            DRY_WET,
        ],
    },
    {
        "id": "audio_formant",
        "label": "Formant",
        "category": "Audio",
        "description": "Formant shift — voice character, independent of pitch",
        "params": [
            ("shift", "Shift", -1.0, 1.0, 0.0, "%+.2f"),
            DRY_WET,
        ],
    },
]


def swift_str(s):
    """Escape a Python string as a Swift string literal body."""
    out = []
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\r":
            out.append("\\r")
        elif ord(ch) < 0x20:
            out.append("\\u{%04X}" % ord(ch))
        else:
            out.append(ch)  # UTF-8 source file: printable unicode stays literal
    return '"' + "".join(out) + '"'


def swift_double(x):
    """Full-precision repr that round-trips and is a valid Swift Double literal."""
    r = repr(float(x))
    if "e" in r or "E" in r:  # e.g. 1e-05 — Swift accepts e-notation but needs digits around it
        r = "%.17g" % float(x)
        if "." not in r and "e" not in r and "E" not in r:
            r += ".0"
    return r


def emit_param(key, label, mn, mx, default, fmt, indent):
    pad = " " * indent
    return (f"{pad}.init(key: {swift_str(key)}, label: {swift_str(label)}, "
            f"min: {swift_double(mn)}, max: {swift_double(mx)}, "
            f"def: {swift_double(default)}, format: {swift_str(fmt)}),")


def emit_effect(eid, label, category, description, params, indent):
    pad = " " * indent
    lines = [f"{pad}EffectDef("]
    lines.append(f"{pad}    id: {swift_str(eid)},")
    lines.append(f"{pad}    name: {swift_str(label)},")
    lines.append(f"{pad}    category: {swift_str(category)},")
    lines.append(f"{pad}    description: {swift_str(description)},")
    if params:
        lines.append(f"{pad}    params: [")
        for p in params:
            lines.append(emit_param(*p, indent + 8))
        lines.append(f"{pad}    ]")
    else:
        lines.append(f"{pad}    params: []")
    lines.append(f"{pad}),")
    return lines


def main():
    manifest_path = os.path.join(ENGINE, "effects", "mcp_manifest.json")
    with open(manifest_path, encoding="utf-8") as f:
        manifest = json.load(f)
    if not isinstance(manifest, list):
        manifest = manifest.get("effects", [])

    lines = [HEADER, "enum EffectCatalog {"]

    # Video effects — manifest order preserved.
    lines.append(f"    // Video effects ({len(manifest)}) — from effects/mcp_manifest.json, manifest order.")
    lines.append("    static let video: [EffectDef] = [")
    categories = []
    for e in manifest:
        cat = e.get("category", "")
        if cat not in categories:
            categories.append(cat)
        params = [(p["name"], p.get("label", p["name"]),
                   p.get("min", 0.0), p.get("max", 1.0),
                   p.get("default", 0.0), p.get("fmt", "%.2f"))
                  for p in e.get("params", [])]
        lines += emit_effect(e["id"], e.get("label", e["id"]), cat,
                             e.get("description", ""), params, 8)
    lines.append("    ]")
    lines.append("")

    # Audio effects — engine vocabulary, hand-authored table above.
    lines.append(f"    // Audio effects ({len(AUDIO_EFFECTS)}) — engine vocabulary ids;")
    lines.append("    // param keys match add_effect_brick / add_audio_multifx_brick.")
    lines.append("    static let audio: [EffectDef] = [")
    for e in AUDIO_EFFECTS:
        lines += emit_effect(e["id"], e["label"], e["category"],
                             e["description"], e["params"], 8)
    lines.append("    ]")
    lines.append("")

    lines.append("    static let all: [EffectDef] = video + audio")
    lines.append("")
    lines.append("    static let byID: [String: EffectDef] =")
    lines.append("        Dictionary(uniqueKeysWithValues: all.map { ($0.id, $0) })")
    lines.append("")
    lines.append("    // Unique video categories, first-appearance order.")
    lines.append("    static let videoCategories: [String] = [")
    for c in categories:
        lines.append(f"        {swift_str(c)},")
    lines.append("    ]")
    lines.append("}")

    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {os.path.relpath(OUT_PATH, REPO_ROOT)}: "
          f"{len(manifest)} video + {len(AUDIO_EFFECTS)} audio effects, "
          f"{len(categories)} categories")


if __name__ == "__main__":
    main()
