#!/usr/bin/env python3
"""Generate docs/LEVERS.md — the engine command contract for the SwiftUI
shell and the Claude design workflow.

Sources (sibling checkout of the desktop repo):
  - src/generated/agent_tools.h   (command names + JSON schemas)
  - effects/mcp_manifest.json     (per-effect params: ranges/defaults)

The rule the doc encodes: UI screens speak engine_command(json) ONLY.
A missing lever is an engine PR, never a bypass.
"""
import json, os, re, sys

ENGINE = os.environ.get("PMS_DESKTOP", os.path.expanduser("~/dev/pop-maker-studio"))

def load_tools():
    src = open(os.path.join(ENGINE, "src/generated/agent_tools.h")).read()
    # tools are embedded as one JSON array string; find the bracketed blob
    m = re.search(r'R"JSON\((.*)\)JSON"', src, re.S)
    if m:
        return json.loads(m.group(1))
    # fallback: parse name/description pairs
    tools = []
    for tm in re.finditer(r'\{"name":\s*"(\w+)",\s*"description":\s*"((?:[^"\\]|\\.)*)"', src):
        tools.append({"name": tm.group(1),
                      "description": tm.group(2).encode().decode("unicode_escape")})
    return tools

def main():
    tools = load_tools()
    fx = json.load(open(os.path.join(ENGINE, "effects/mcp_manifest.json")))
    out = ["# Engine levers — the complete command surface",
           "",
           "*Generated by tools/gen_levers.py from the desktop engine's",
           "generated manifests. Do not edit by hand; regenerate.*",
           "",
           "The iOS shell (and any Claude design workflow building screens)",
           "drives the engine exclusively through `pms_command(json) -> json`.",
           "These are the commands. If a screen needs a lever that isn't",
           "here, that's an engine change (add handler, regen), never a",
           "bypass into engine internals.",
           "",
           f"## Commands ({len(tools)})",
           ""]
    for t in sorted(tools, key=lambda x: x["name"]):
        desc = t.get("description", "").split("\n")[0][:160]
        out.append(f"- **`{t['name']}`** — {desc}")
    effects = fx if isinstance(fx, list) else fx.get("effects", [])
    out += ["", f"## Effects ({len(effects)}) — via `add_effect_brick` / `set_clip_fx`", ""]
    for e in effects:
        ps = ", ".join(f"`{p['name']}` [{p.get('min','?')}–{p.get('max','?')}] "
                       f"(default {p.get('default','?')})"
                       for p in e.get("params", []))
        out.append(f"- **{e.get('label', e.get('id'))}** (`{e.get('id')}`, "
                   f"{e.get('category','?')}) — {ps if ps else 'amount only'}")
    out += ["", "## Engine lifecycle (not agent tools — C ABI, see pms_engine.h)", "",
            "- `pms_create / pms_destroy` — engine instance",
            "- `pms_tick(dt)` — advance timers, pump workers",
            "- `pms_render(target_texture, w, h)` — composite the current frame",
            "- `pms_command(json) -> json` — every lever above",
            "- `pms_poll_events() -> json[]` — progress, meters, tracker state, take events",
            "- `pms_submit_camera_frame / pms_submit_mic_block` — capture intake",
            "- `pms_set_asset_root / pms_model_status` — bundle + downloaded model packs",
            ""]
    path = os.path.join(os.path.dirname(__file__), "..", "docs", "LEVERS.md")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    open(path, "w").write("\n".join(out) + "\n")
    print(f"wrote docs/LEVERS.md: {len(tools)} commands, {len(effects)} effects")

if __name__ == "__main__":
    main()
